name: Debug SSH Connection

on:
  workflow_dispatch: # Manually triggered

jobs:
  debug-ssh:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Print EC2_HOST and EC2_SSH_KEY details
    - name: Print Debug Info
      run: |
        echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
        echo "EC2_SSH_KEY (first 5 lines):"
        echo "${{ secrets.EC2_SSH_KEY }}" | head -n 5

    # Step 2: Write the SSH key to a file for use in SSH command
    - name: Write SSH Key to File
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    # Step 3: Test SSH Connection
    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection to ${{ secrets.EC2_HOST }}..."
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} echo "SSH connection successful!"
