name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Docker Buildx
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t naturemate/backend:latest .
        docker push naturemate/backend:latest

    # Step 5: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Stop and remove existing container
          docker stop backend || true
          docker rm backend || true

          # Pull the latest Docker image
          docker pull naturemate/backend:latest

          # Run the Docker container
          docker run -d --name backend -p 8080:8080 naturemate/backend:latest
